### ISSUE TITLE
Readout.py "invalid argument"

### ISSUE THREAD

**Issue by joshuajayg** [jorticus/pymate#17]
I cloned the repo to my PiZeroW, upgraded all my packages, set the settings.py serial port to "/dev/serial0" which should be my hardware serial port, then ran readout.py.  I got the following log:
`MATE emulator (MX)
Traceback (most recent call last):
  File "readout.py", line 9, in <module>
    bus = MateNET(SERIAL_PORT)
  File "/home/pi/Downloads/pymate/pymate/matenet/matenet.py", line 60, in __init__
    self.port = MateNETSerial(port, supports_spacemark)
  File "/home/pi/Downloads/pymate/pymate/matenet/matenet_ser.py", line 48, in __init__
    self.ser.timeout = 1.0
  File "/home/pi/.local/lib/python2.7/site-packages/serial/serialutil.py", line 368, in timeout
    self._reconfigure_port()
  File "/home/pi/.local/lib/python2.7/site-packages/serial/serialposix.py", line 438, in _reconfigure_port
    [iflag, oflag, cflag, lflag, ispeed, ospeed, cc])
termios.error: (22, 'Invalid argument')
`

I don't have anything hooked to my serial port yet but figured I would just get the typical "MX device not found."

**Comment by joshuajayg** [comment]
Disregard.  Using the wrong port.
