### ISSUE TITLE
error parity_mark

### ISSUE THREAD

**Issue by wawanwiratno** [jorticus/pymate#2]
Hi, 
this is impressive work, thanks for sharing
Im using raspberry pi 3, Jessie, python 2.7
I just run readout.py but got following error

_root@monitoring:/home/pi/pymate-master# python readout.py 
MATE emulator (MX)
Traceback (most recent call last):
  File "readout.py", line 10, in <module>
    mate.scan(0)
  File "/home/pi/pymate-master/matenet/mx.py", line 130, in scan
    devid = super(MateMX, self).scan(port)
  File "/home/pi/pymate-master/matenet/matenet.py", line 185, in scan
    result = self.query(0x00, port=port)
  File "/home/pi/pymate-master/matenet/matenet.py", line 196, in query
    resp = self.send(MateNET.TYPE_QUERY, addr=reg, param=param, port=port)
  File "/home/pi/pymate-master/matenet/matenet.py", line 156, in send
    self._send(packet.to_buffer())
  File "/home/pi/pymate-master/matenet/matenet.py", line 88, in _send
    self._write_9b(data[0], 1)
  File "/home/pi/pymate-master/matenet/matenet.py", line 70, in _write_9b
    self.ser.setParity(PARITY_MARK if bit8 else PARITY_SPACE)
  File "/usr/lib/python2.7/dist-packages/serial/serialutil.py", line 347, in setParity
    if self._isOpen: self._reconfigurePort()
  File "/usr/lib/python2.7/dist-packages/serial/serialposix.py", line 376, in _reconfigurePort
    raise ValueError('Invalid parity: %r' % self._parity)
ValueError: Invalid parity: 'M'_

seems like PARITY_MARK is not supported,
Any clues?

**Comment by jorticus** [comment]
Could you open a python shell on your Pi and run the following:

```
ser = Serial('/dev/tty???', 9600)   # Replace ??? with your serial port
ser.PARITIES
```

If ser.PARITIES contains 'M' and 'S', then it's probably a bug in the Raspberry Pi serial library.

As a work-around, you can simply replace lines 56 to 59 in [pymate/matenet.py](https://github.com/jorticus/pymate/blob/master/matenet/matenet.py#L56) with `self.supports_spacemark = False`. This will cause my library to fall back to a work-around mode for systems that don't support Mark/Space parity.

**Comment by jorticus** [comment]
Actually don't worry about running that, I see the bug. I'll think of a way to fix it but in the mean time the work-around above should solve your issue.

**Comment by wawanwiratno** [comment]
Hi Jared,
yes correct, I run this code I got 'M' and 'S'
`root@monitoring:/home/pi# python serial_test.py 
('N', 'E', 'O', 'M', 'S')`
then I tried your work-around:
`root@monitoring:/home/pi/pymate-master# python readout.py 
MATE emulator (MX)
Traceback (most recent call last):
  File "readout.py", line 10, in <module>
    mate.scan(0)
  File "/home/pi/pymate-master/matenet/mx.py", line 132, in scan
    raise RuntimeError("Attached device is not an MX unit!")
RuntimeError: Attached device is not an MX unit!`

Im using opto isolated schematic, with MX 48vdc system, but I see the pin vcc at MX still using 24v, 
so your schematic still can be used right?
any clues what my caused this error?

Thanks

**Comment by jorticus** [comment]
Okay the most likely cause for that is basically the library isn't getting anything back from the Pi.

Have you confirmed you can access the MX with an actual Mate? I think you may need to enable the bus via a setting somewhere if you haven't already.

The schematic should work fine at 24/48V, though the resistor values really depend on the opto-isolator you're using. Perhaps the Pi VCC isn't enough to power your opto-isolator. Do you have an oscilloscope or logic analyzer handy? I'd put that on the RX/TX lines going into the Pi and see if you can see any data flowing. (Careful attaching anything on the MX side, since that's 24/48V!)

Also you could try sending a raw scan command - if the following returns None, then the unit isn't responding: (This is different than calling scan on a MateMX() object)

```
test = Mate(port)
test.scan()    # This will either return None if no devices are connected, or an integer specifying the connected device type.
```

**Comment by wawanwiratno** [comment]
Hi Jared,
Just back from weekend traveling, 
I think my circuit have a problem, I will make new one, Im using pc817 optocoupler
will let you now after I test with mate3.
Thanks for your supports

**Comment by wawanwiratno** [comment]
Hi Jared,
Just finish rework on the circuit, I add extra led to visually check if its not break 
![whatsapp image 2017-03-06 at 5 28 10 pm](https://cloud.githubusercontent.com/assets/26109047/23606276/921e778c-0292-11e7-9b20-15b10482de16.jpeg)
I jumper power pin 1 and 2, mate need this 
it can run with mate 3, so its mean there is no problem with the circuit, right?
but then I replace with PC using serial to usb FTDI and try to run your suggestion
`root@monitoring:/home/pi/pymate-master# python readout.py 
MATE emulator (MX)
Traceback (most recent call last):
  File "readout.py", line 10, in <module>
    mate.scan(0)
  File "/home/pi/pymate-master/matenet/mx.py", line 130, in scan
    devid = super(MateMX, self).scan(port)
  File "/home/pi/pymate-master/matenet/matenet.py", line 186, in scan
    result = self.query(0x00, port=port)
  File "/home/pi/pymate-master/matenet/matenet.py", line 197, in query
    resp = self.send(MateNET.TYPE_QUERY, addr=reg, param=param, port=port)
  File "/home/pi/pymate-master/matenet/matenet.py", line 160, in send
    data = self._recv()
  File "/home/pi/pymate-master/matenet/matenet.py", line 145, in _recv
    return MateNET._parse_packet(rawdata)
  File "/home/pi/pymate-master/matenet/matenet.py", line 114, in _parse_packet
    raise RuntimeError("Error receiving mate packet - Received packet too small")
RuntimeError: Error receiving mate packet - Received packet too small
root@monitoring:/home/pi/pymate-master# python readout.py 
MATE emulator (MX)
Traceback (most recent call last):
  File "readout.py", line 10, in <module>
    mate.scan(0)
  File "/home/pi/pymate-master/matenet/mx.py", line 132, in scan
    raise RuntimeError("Attached device is not an MX unit!")
RuntimeError: Attached device is not an MX unit!
`
first time run the error is packet too small, second run is not detected
then try scan:
`from matenet import Mate

test = Mate('/dev/ttyUSB0')
test.scan(0)
`
return nothing

something I have missed?
thanks

**Comment by wawanwiratno** [comment]
Hi Jared, what serial converter did you use?
Im afraid there is some delay using FTDI usb to serial, unfortunately I dont have oscilloscope :(

**Comment by jorticus** [comment]
I think I used a CP210x USB to serial, but I can't remember 100%. 

Yes, if the MATE3 can communicate through the opto-isolator circuit, that means it should be working. There shouldn't be any problems with delays - I know my parity hack adds quite a lot of delay between bytes, but my unit had no problems responding to the data. The parity hack might not even be required for the FTDI converter, if it supports Mark/Space parity.

Without an oscilloscope or logic analyzer it will be tricky to diagnose what's happening, and I don't have any of the equipment with me so I can't test it here either.

- Have you tried swapping RX and TX?
- How have you connected everything together? (I assume Raspberry Pi <> FTDI <> Opto Isolator <> MX Charger?) 
- What model charger do you have? I think some of their latest models use a newer protocol that isn't compatible with my library.

**Comment by wawanwiratno** [comment]
Hi Jared,
-Yes I have swap Rx anf Tx pin, but still no luck
-yes all connected and checked all pin have a voltage using voltmeter
- the charger is Flexmax60 FM60 150vdc input
so if the newer version using different protocol, its not my lucky day :(
they changed it because of you I think, (kidding...:)
next step I'll get the oscilloscope, but not in short time, need to allocate my financial budget :(
thanks anyway

**Comment by merlininthewoods** [comment]
Hello

I am very excited to get this working!  I have had the same problems in this issue.  I used the workaround you suggested in your first post on it and now have the issue on wawanwiratno's second post!

I have tested the opto-coupler circuit by connecting it to a 24v supply and shorting rx and tx and I am able to echo data through it, so I think thats OK.

I am a bit confused about which is Rx and Tx on the MX side.  Your circuit diagram shows the Rx going to the LED and the Tx going to the transistor which seems the wrong way round to me.  To be clear which pin is the LED connected to on your working setup?  I have tried swapping them without any success but it would be good to rule this out as part of the problem.

I have also tried:
```
from matenet import Mate
test = Mate('/dev/ttyUSB0')
for x in range(10):
	print x
	test.scan(x)
```
with no output from scan

Also I have never had a Mate connected to it so this could be the problem.  I don't suppose you have the code needed to initialise it to work with the Mate (I don't have access to one).

Thanks for your work on this.

**Comment by sagreen83** [comment]
Has anyone gotten this to work? I've built the optocoupler and tested its function. It seems to be working. I'm having the same problems as others.

My configuration is:
Raspberry PI -> USB converter -> Optocoupler -> Flexmax 80

My USB converter uses 3.3v on the TX and RX lines so I changed the 1K resistor to a 470. This gives me a full 22v to 0 volt swing on the Output side of the optocoupler.

To get the matenet.py to work, I had to make the change talked about @ https://github.com/jorticus... to correct the "self.supports_spacemark = False " issue.

In order to test, I've been trying to get pymate/srv1/collector.py running.

When I start this program I get an error "RuntimeError: Attached device is not an MX unit!"

I put an oscilloscope on the TX output of the optocoupler and can see real nice 22v to 0v communication. It looks like its sending serial data. When I move the scope to the RX side of the optocoupler, I never see any response on the 22v side.

Its possible that the Flexmax uses a different protocol for discovery than the OP's MX unit. The flexmax was a replacement for the MX.

**Comment by jorticus** [comment]
@sagreen83 have you previously connected a MATE to your Flexmax? I know there's some kind of initialization process which is missing from the python script.

The MX unit I have is no longer listed on their site so perhaps the protocol has changed, but unfortunately I don't have a Flexmax myself to test with. If you feel up to the challenge it would be very helpful to have some oscilloscope traces of the communications between your MATE and Flexmax unit. I could then verify that they use the same protocol.

**Comment by jorticus** [comment]
For others that may stumble here, this is what I observed the MATE send to my MX when it first powers up:
```
TX:  80 02 00 00 00 00 00 02  -- Query reg 00 00, port 00 (Scan)
RX:  83 00 03 00 07           -- Device is 00 03 (MX)
Equivalent to mate.query(0x0000)  or  mx.scan()

TX:  80 02 00 3C 00 00 00 3E  -- Query reg 003C, port 00 - STATUS/FX/MODE : Charge control
RX:  83 00 00 00 03           -- Value 00 00 (Off)
Equivalent to mate.query(0x003C)  or  print fx.charge_control
```

If you're getting 'Attached device is not an MX unit!' the best thing I can suggest is to run the following:
```
mate = MateMX('/dev/ttyUSB0') # COM port of your choice
print "Scan:", mate.query(0x0000)
```
If it prints "Scan: None", then it's simply not getting any data back. Anything else indicates a bug in my code.

**Comment by jorticus** [comment]
Hi all, I think I've finally got to the bottom of this!

It looks like that with some serial adapters my Even/Odd parity hack didn't work because the OS buffers the bytes, causing the parity to not be applied to the correct byte. I've pushed a hacky workaround to the repo which inserts a delay between each byte (roughly half a byte delay).

Please pull the latest version of this library and let me know if this helps!

You can try tweaking the `FUDGE_FACTOR` in matenet.py. Start with 0.5 seconds and work down from there.

Also, for those of you hit by the weird spacemark error, you can now pass it in as a parameter:
`m = MateMX('COM1', supports_spacemark=False)`

**Comment by sagreen83** [comment]
> @sagreen83 have you previously connected a MATE to your Flexmax? I know there's some kind of initialization process which is missing from the python script.
> 
> The MX unit I have is no longer listed on their site so perhaps the protocol has changed, but unfortunately I don't have a Flexmax myself to test with. If you feel up to the challenge it would be very helpful to have some oscilloscope traces of the communications between your MATE and Flexmax unit. I could then verify that they use the same protocol.

I've never had a Mate. Matter of fact, I've been scanning ebay for the past 2 weeks trying to find one that isnt $400 :) I wont be at the cabin until next weekend, but will try your new version and grab both OScope traces and Logic Analyzer logs.

Thanks so much for dragging this back out!

Scott...

**Comment by sagreen83** [comment]
Ok, a couple OScope captures of TX during a scan...

Here is a trace of the TX line prior to your changes (-1 version)

![prev-scope2](https://user-images.githubusercontent.com/3307290/47053906-d41ecd00-d174-11e8-9b7e-db45cf625f66.png)

This is a trace of the TX line with your latest mods... (current version). Note, I've made no changes to FUDGE_FACTOR

![new-scope1](https://user-images.githubusercontent.com/3307290/47053957-029ca800-d175-11e8-9253-ab5818c6689e.png)

Neither of these traces look like the one in your picture above.

Scott...

**Comment by sagreen83** [comment]
Here is another trace. This one is from a PC using the same USB adapter. The PC allows the default PARITY_MARK option..

![pc-scope1](https://user-images.githubusercontent.com/3307290/47124529-021f1280-d244-11e8-8b4e-4cac6d545a35.png)

I assume this is the type of trace we are shooting for?

Scott...

**Comment by jorticus** [comment]
Those traces look like what I would expect, both the ones on your PC and the one on the RPi (after my changes). The first blip is the "start of packet" marker with bit 9 set, then the following burst is each byte of the payload with bit 9 cleared. Unfortunately I can't tell from your traces whether bit 9 is being set properly (I don't suppose you have a serial decoder plugin?).

According to the manual for the Flexmax, it should be compatible with the MATE2, which is what this python library emulates.

Are you sure you have TX/RX around the right way? Pin 3 of the RJ45 should be PC(TX)->MX, Pin 6 should be MX->PC(RX).

Ah I really wish I had a MATE to test with right now :( 
It might be a while before I get a chance to look into this properly...

**Comment by sagreen83** [comment]
Ok, possibly some progress. I now have the logic analyzer displaying proper characters using the RPi. Seems that my scope leads were causing a problem. Possible ground issue between the 2. Anyway....

Here is a complete logic dump of the first packet...

![complete](https://user-images.githubusercontent.com/3307290/47190885-82f41200-d309-11e8-9b78-491d32f989d1.png)

Here is what the first blip looks like...

![start](https://user-images.githubusercontent.com/3307290/47190894-90a99780-d309-11e8-8f51-7dd5cf8ed1a9.png)

This is what the rest of the characters look like...

![2](https://user-images.githubusercontent.com/3307290/47190902-9bfcc300-d309-11e8-9bd2-791d1b0ead2a.png)


If I am reading this correctly the 9th bit is set on the first blip, and cleared on the remaining bytes. Thats whats likely causing the framing error I see on the logic analyzer. Seems like this is outputting the proper byte sequence.

Scott...

**Comment by sagreen83** [comment]
Ok, making more progress... After changing out more resisters I have data coming back to the PC. Havent tried the RPi yet... I'm still getting "no response from MX". Seems like the FlexMax is returning different data than an MX during discovery.

After the scan the Flexmax80 returns "02 02 03 00 07"

Here is a logic trace

![capture](https://user-images.githubusercontent.com/3307290/47261500-49044680-d496-11e8-9e45-6e1e8363e302.png)

Will keep trying. Looking at the initialization code next.

Scott...

**Comment by sagreen83** [comment]
Changed the line 
>     DEVICE_MX = 3
to
>     DEVICE_MX = 515

Now its reading packets. I am using the code collector.py from the srv1/ directory. Its collecting data, but there is no downstream process to read the data that the server is trying to send. So, I'll have to create a quick and dirty reader to just display what its reading. Maybe there is already one in the distro.

This is what the server is displaying.

Next logpage: 2018-10-22 00:05:00
Upload: {'data': 'iIKDAAI/AgABAfwC9Q==', 'extra': {'chg_w': 193.0}, 'type': 'mx-status', 'ts': '2018-10-21T14:42:44.938000', 'tz': -18000}

Not sure yet what this should look like, but the fact that I'm reading data now is promising!

More to follow.

Scott...

**Comment by sagreen83** [comment]
Great news!

I just swapped from the PC (using PARITY_MARK) to the RPi (using parity hack) and its getting the same results as the PC. No changes to resistors either (PC uses 5v and RPi uses 3.3v).

Now I can leave the RPi hooked up to the Flexmax 80 and do coding from home. This is the best development to date!

Scott...

**Comment by jorticus** [comment]
Excellent! I think I must be misunderstanding the second byte in "02 02 03 00 07". I've updated the repo to mask that out until I understand what it does. 

FYI the counterpart to the collect.py is "srv2":
https://github.com/jorticus/pymate/blob/master/srv2/receiver.py
It's very simple and has no authentication, but it's good enough for testing. You can set it up permanently through uWSGI.
